### ISSUE TITLE
Looses configuration and game progress between restarts

### ISSUE THREAD

**Issue by lukasfink1** [flathub/com.agateau.PixelWheels#1]
The application doesn’t maintain its data across restarts. Changes to the configuration, unlocked cars/maps and the leader-board ranks get reset with each restart.

I reproduced this issue both on SteamOS and on Arch Linux.

**Comment by hfiguiere** [comment]
The flatpak it likely missing a "persist" to save that directory as it is in Java.

**Comment by agateau** [comment]
Oh, I need to look up on that. Pixel Wheels indeed saves its data in files stored in ~/.local/share/pixelwheels.

**Comment by hfiguiere** [comment]
then you need `--persist=.local`

This is definitely not XDG compliant.

**Comment by agateau** [comment]
I just added support for `XDG_DATA_HOME` and `XDG_CONFIG_HOME`. In the next version Pixel Wheels will store progress in `$XDG_DATA_HOME/pixelwheels/` and fall back to `$HOME/.local/share/pixelwheels/` if `$XDG_DATA_HOME` is not set.

Is the lack of support for `$XDG_DATA_HOME` what you meant with "This is definitely not XDG compliant"?
